'use client';

import Head from 'next/head';
import { brand } from '../lib/brand';

interface SEOHeadProps { title: string; description: string; keywords?: string; canonicalUrl?: string; ogImage?: string; ogType?: 'website' | 'article'; publishedTime?: string; modifiedTime?: string; author?: string; category?: string; tags?: string[]; }

export default function SEOHead({ title, description, keywords, canonicalUrl, ogImage = `${brand.siteUrl}${brand.banner}`, ogType = 'website', publishedTime, modifiedTime, author = brand.name, category, tags = [] }: SEOHeadProps) {
  const fullTitle = title.includes(brand.name) ? title : `${title} | ${brand.name}`;
  const url = canonicalUrl || brand.siteUrl;
  const structuredData = ogType === 'article' ? { '@context': 'https://schema.org', '@type': 'Article', headline: title, description, image: ogImage, author: { '@type': 'Organization', name: author }, publisher: { '@type': 'Organization', name: brand.name, logo: { '@type': 'ImageObject', url: `${brand.siteUrl}${brand.logo}` } }, datePublished: publishedTime, dateModified: modifiedTime || publishedTime, mainEntityOfPage: { '@type': 'WebPage', '@id': url }, articleSection: category, keywords: tags.join(', '), inLanguage: 'en-KE' } : { '@context': 'https://schema.org', '@type': 'WebSite', name: brand.name, description: brand.description, url: brand.siteUrl, potentialAction: { '@type': 'SearchAction', target: { '@type': 'EntryPoint', urlTemplate: `${brand.siteUrl}/blog?search={search_term_string}` }, 'query-input': 'required name=search_term_string' } };
  return <Head><title>{fullTitle}</title><meta name="description" content={description} />{keywords && <meta name="keywords" content={keywords} />}<meta name="author" content={author} /><link rel="canonical" href={url} /><meta property="og:title" content={fullTitle} /><meta property="og:description" content={description} /><meta property="og:type" content={ogType} /><meta property="og:url" content={url} /><meta property="og:image" content={ogImage} /><meta property="og:image:alt" content={`${brand.name} — ${title}`} /><meta property="og:site_name" content={brand.name} /><meta property="og:locale" content="en_KE" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content={fullTitle} /><meta name="twitter:description" content={description} /><meta name="twitter:image" content={ogImage} /><meta name="application-name" content={brand.name} /><meta name="theme-color" content="#0e7490" /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /></Head>;
}
